### ISSUE TITLE
Make locations and photos belong to a user

### ISSUE THREAD

**Issue by annescripthero** [axnickle/blog_travel_map#12]
Relates to #3 

Right now, we have a `User` model that is independent of any of the other models. We have no way of knowing which `Location`s and which `Photo`s belong to which `User`. That's okay if there is only 1 user in this app, but what if we have a second user? Things will get messy fast! Let's solve this by making `Location`s and `Photo`s belong to a `User`. 

This list is WIP (Work In Progress) ...
- [x] check out your master branch, pull it, then create a new branch called `12_add_user_relationships`
- [x] write a migration to add a `user_id` to `Photo` and to `Location`: `rails g migration add_user_id_to_locations_and_photos`
- [x] update the relationships in all 3 models, adding both `has_many`s and `belongs_to`s where needed. 
- [x] revisit the uniqueness validation in your `Location` model. Scope this down to being unique only within a user.

**Comment by axnickle** [comment]
We may need to over the last check box a bit more in detail.
