### ISSUE TITLE
set up devise and user model

### ISSUE THREAD

**Issue by annescripthero** [axnickle/blog_travel_map#6]
Relates to #3 

Goal: create the concept of a `User` and make it so that users can sign up for an account, sign in, and sign out.

- [x] create branch for this work: `git checkout -b 6_set_up_devise`
- [x] set up [devise gem](https://github.com/heartcombo/devise) for authentication -- and in the process, set up the `User` model
    - [x] include an `admin` boolean in the devise migration
    - [x] include a `first_name` string in the devise migration
    - [x] include a `last_name` string in the devise migration
    - [x] include an `email` string in the devise migration
- [x] lock down all controller actions except `show` for 
- [x] scope all other actions (create, new, edit, update) to the `current_user`
- [x] create a pull request in github from this branch to `master` and ask for a code review

**Comment by axnickle** [comment]
Would you mind clarifying on why we'd want to "lock down all controller actions except `show`"? 🤔

**Comment by axnickle** [comment]
![Screen Shot 2020-06-17 at 10 29 38 PM](https://user-images.githubusercontent.com/57374526/84971832-98779b80-b0eb-11ea-9787-a7a1fe38224a.png)
![Screen Shot 2020-06-17 at 10 30 06 PM](https://user-images.githubusercontent.com/57374526/84971834-98779b80-b0eb-11ea-952c-bc0c0ffed62d.png)
![Screen Shot 2020-06-17 at 10 30 17 PM](https://user-images.githubusercontent.com/57374526/84971836-99103200-b0eb-11ea-87c8-edcf94e3d901.png)

**Comment by annescripthero** [comment]
Awesome!! Great work!
