### ISSUE TITLE
populate database with location data from csv

### ISSUE THREAD

**Issue by annescripthero** [axnickle/blog_travel_map#7]
Relates to #3

Goal: get the data from your csv file into your local and production (heroku) databases with a rake task.

- [x] create a branch for this work `git checkout -b 7_populate_location_data`
- [x] commit something, push the branch to github and make a pull request
- [x] make sure your excel file is up to date with all fields from your `locations` table. Check your schema.rb to make sure.
- [x] export that to csv
- [x] write a validation in the `Location` model so that only locations with unique names can be saved [(hint)](https://guides.rubyonrails.org/active_record_validations.html#uniqueness)
- [x] make the rake task smart enough to only create new records if the location's name is unique. [(hint: ruby's `next`)](https://medium.com/@ryanflach/next-and-break-in-ruby-4bf9daf5322d)
- [x] use [ruby's CSV class](https://ruby-doc.org/stdlib-2.6.1/libdoc/csv/rdoc/CSV.html) create a [rake task](https://dev.to/vinistock/customizing-rails-rake-tasks-3bg5) that opens your csv, reads each row, and saves a new location object to the database for each row in the csv file. 
- [x] run your new rake task tot populate your super awesome _real_ data!
- [x] ask for a code review of you PR on github

**Comment by annescripthero** [comment]
Example rake task
```ruby
# lib/tasks/populate_locations.rake

namespace :db do
  desc "Populate Location data from CSV file"

  task :populate_locations do

    [Your code goes here]

  end
end
```

Run this from your command line like: `rake db:populate_locations`

**Comment by annescripthero** [comment]
I recently did a task similar to this and am glad to pair with you on it. (Note to myself: see `lib/script_save/convert_ndc_to_gsn_from_csv.rb`)

**Comment by annescripthero** [comment]
If you want to check that your validation code is working, there is a nifty method called `.valid?`. In this example, we want the `name` field to be required for a `Location` object. If you've added the code to your `Location` model, you can check it like this:

Open a terminal tab and run `rails c`. Once inside:
```ruby
# create a new instance of Location, without giving it a name
location = Location.new()

# ask if this nameless location is valid
location.valid?

# you should see
=> false

# now give the location a name
location.name = 'The Louvre'

# check to see if the location is valid now
location.valid?

# you should see
=> true
```
This is checking that your `location.name` is present. We also need to make sure it is _unique_. If you try to _save_ two records with the same name, you should see an error.

```ruby
# save your first location
location.save

# try to create a second location that has the same name
location2 = Location.create!(name: 'The Louvre')

# you should get an error that warns you about uniqueness
```

Remember the point of making a validation that requires the presence of an attribute is to help you make sure that you are getting all of the data you need to make your app work. Adding a uniqueness constraint helps to make sure users don't enter duplicate data. For your project, you shouldn't need any other uniqueness constraints on the `Location` model. But think about what other pieces of data are absolutely necessary and should have a `presence: true`.

**Comment by annescripthero** [comment]
FYI if we want to (or need to ) look up lat/long for cities, this is a resource: https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/table/

**Comment by axnickle** [comment]
I ran all the commands in Rails C, results are exactly as what you've described above 👍

**Comment by axnickle** [comment]
As for you last question on `presence: true` , wouldn't we want the the longitude and latitude to have a 'presence : true'?

**Comment by annescripthero** [comment]
Sure, go for it!
